### ISSUE TITLE
Cannot define property:48, object is not extensible.

### ISSUE THREAD

**Issue by renatho** [twolfson/grunt-fontsmith#28]
When I run the grunt task, call this fatal error:
Cannot define property:48, object is not extensible.

I think that it is incompatible with my node version: v0.12.0

**Comment by twolfson** [comment]
I was waiting on https://github.com/twolfson/fontsmith/pull/10. It looks like an update to the PR has been posted. I will take a look at this by the end of the weekend.

**Comment by twolfson** [comment]
This has been fixed/released in `0.10.0`.
